import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/pages/NavBar";
import Script from "next/script";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/ConvexClientProvider";
import { viVN } from "@clerk/localizations";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={viVN}>
      <ConvexClientProvider>
        <html lang="en">
          <body className={`${inter.className} antialiased`}>
            <Navbar></Navbar>
            <Toaster />
            {children}
            <Script
              src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
              async
              id="MathJax-script"
            ></Script>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
